import differentiation_real_functions_one_variable_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace differentiation_real_functions_one_variable_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end differentiation_real_functions_one_variable_theorem_canonical_lane_mathlib
end HautevilleHouse
